version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  web:
    image: projectname:1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DEBUG: 'true'